"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";

const statuses = ["Submitted", "Under Review", "Needs Revision", "Approved", "Declined"];

export default function OsasMonitoringTab({ showToast }) {
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [status, setStatus] = useState("Submitted"); const [note, setNote] = useState("");
  const load = async () => { const res = await fetch("/api/osas/event-proposals", { cache: "no-store" }); const json = await res.json(); if (res.ok && json.ok) setRows(json.data); else showToast?.({ title: "Load failed", description: json?.error || "Unable to load OSAS submissions." }, true); };
  useEffect(() => { const timer = setTimeout(() => { load(); }, 0); return () => clearTimeout(timer); }, []);
  const select = async (item) => { const res = await fetch(`/api/osas/event-proposals/${item.id}`, { cache: "no-store" }); const json = await res.json(); if (res.ok && json.ok) { setSelected(json.data); setStatus(json.data.status); setNote(""); } };
  const save = async () => { const res = await fetch(`/api/osas/event-proposals/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, note }) }); const json = await res.json(); if (!res.ok || !json.ok) return showToast?.({ title: "Update failed", description: json?.error || "Unable to save." }, true); showToast?.({ title: "Proposal updated", description: "The student timeline was updated." }); await load(); await select(json.data); };
  return <div className="grid h-full gap-4 lg:grid-cols-[1fr_420px]"><section className="rounded-brand bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">OSAS Monitoring</h2><p className="mb-4 text-sm text-gray-600">Review student Event Proposals and publish status updates.</p><div className="space-y-2">{rows.map((item) => <button key={item.id} onClick={() => select(item)} className="block w-full rounded border p-3 text-left text-sm hover:bg-gray-50"><strong>{item.title}</strong><span className="ml-2 text-gray-600">{item.status}</span><p className="text-gray-600">{item.student_name} · {item.organization_name}</p></button>)}{!rows.length && <p className="text-sm text-gray-600">No event proposals submitted.</p>}</div></section><aside className="rounded-brand bg-white p-5 shadow-sm">{selected ? <><h3 className="font-bold">{selected.title}</h3><a className="mt-2 block text-sm text-pup-maroon underline" target="_blank" href={`/api/osas/event-proposals/${selected.id}?file=1`}>Open proposal PDF</a><select className="mt-4 w-full rounded border p-2" value={status} onChange={(e) => setStatus(e.target.value)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select><textarea className="mt-3 w-full rounded border p-2 text-sm" placeholder="Student-visible update" value={note} onChange={(e) => setNote(e.target.value)} /><Button className="mt-3 bg-pup-maroon text-white" onClick={save}>Publish update</Button><ol className="mt-4 border-l pl-3 text-sm">{selected.updates?.map((update) => <li key={update.id} className="mb-2"><strong>{update.status}</strong> — {update.message}</li>)}</ol></> : <p className="text-sm text-gray-600">Select a proposal to review it.</p>}</aside></div>;
}
