import { query, queryOne, transaction } from "./postgres.js";
export async function listAllModules({category}={}) { return query(category?"SELECT * FROM modules WHERE category=$1 ORDER BY sort_order":"SELECT * FROM modules ORDER BY category,sort_order", category?[category]:[]); }
export async function getModuleById(id){return queryOne("SELECT * FROM modules WHERE id=$1",[id]);}
export async function getOfficeModules(id){return query("SELECT m.*,om.enabled,om.config,COALESCE(om.sort_order,m.sort_order) effective_sort_order FROM modules m JOIN office_modules om ON om.module_id=m.id WHERE om.office_id=$1 AND om.enabled=true ORDER BY m.category,effective_sort_order",[id]);}
export async function getAllOfficeModuleAssignments(id){return query("SELECT m.*,COALESCE(om.enabled,false) enabled,om.config,COALESCE(om.sort_order,m.sort_order) effective_sort_order FROM modules m LEFT JOIN office_modules om ON om.module_id=m.id AND om.office_id=$1 ORDER BY m.category,m.sort_order",[id]);}
export async function isModuleEnabled(o,m){const r=await queryOne("SELECT enabled FROM office_modules WHERE office_id=$1 AND module_id=$2",[o,m]);return !!r?.enabled;}
export async function setOfficeModules(o,ids=[]){const ms=await query("SELECT id,is_system FROM modules");const e=new Set(ids.map(String));await transaction(async({query:run})=>{for(const m of ms)await run("INSERT INTO office_modules(office_id,module_id,enabled,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(office_id,module_id) DO UPDATE SET enabled=EXCLUDED.enabled,updated_at=NOW()",[o,m.id,m.is_system||e.has(m.id)]);});return getOfficeModules(o);}
export async function enableModule(o,m){await query("INSERT INTO office_modules(office_id,module_id,enabled) VALUES($1,$2,true) ON CONFLICT(office_id,module_id) DO UPDATE SET enabled=true",[o,m]);}
export async function disableModule(o,m){const x=await getModuleById(m);if(x?.is_system)throw new Error(`Module '${m}' is a system module and cannot be disabled.`);await query("UPDATE office_modules SET enabled=false WHERE office_id=$1 AND module_id=$2",[o,m]);}
export async function getEnabledModuleIds(o){return (await query("SELECT module_id FROM office_modules WHERE office_id=$1 AND enabled=true ORDER BY sort_order",[o])).map(r=>r.module_id);}
export async function getModuleConfigMatrix(){const [offices,modules,rows]=await Promise.all([query("SELECT id,short_name,accent_color,status FROM offices ORDER BY created_at"),query("SELECT * FROM modules ORDER BY category,sort_order"),query("SELECT office_id,module_id,enabled,config FROM office_modules")]);const assignments={};for(const r of rows)(assignments[r.office_id]??={})[r.module_id]=r;return {offices,modules,assignments};}
